blank_issues_enabled: false
contact_links: []

issue_templates:
  - name: âœ¨ Feature
    description: ìƒˆë¡œìš´ ê¸°ëŠ¥ ê°œë°œì„ ìœ„í•œ ì´ìŠˆ
    file: feature-request.yml

  - name: ğŸ BugFix
    description: ë²„ê·¸ ìˆ˜ì • ì‘ì—…ì„ ìœ„í•œ ì´ìŠˆ
    file: Bug-Report.yml

  - name: ğŸ“ƒ Docs
    description: ë¬¸ì„œ ì‘ì„± ë° ìˆ˜ì • ì‘ì—… ì´ìŠˆ
    file: docs-task.yml

  - name: âš™ Setting
    description: ê°œë°œ í™˜ê²½ ì„¤ì • ê´€ë ¨ ì´ìŠˆ
    file: setting-task.yml

  - name: ğŸŒ Deploy
    description: ë°°í¬ ê´€ë ¨ ì‘ì—…ì„ ìœ„í•œ ì´ìŠˆ
    file: deploy-task.yml

  - name: ğŸ“¬ API
    description: ì„œë²„ API í†µì‹  ê´€ë ¨ ì‘ì—…
    file: api-task.yml

  - name: âœ… Test
    description: í…ŒìŠ¤íŠ¸ ì½”ë“œ ì‘ì„± ë° í…ŒìŠ¤íŠ¸ í™˜ê²½ êµ¬ì¶•
    file: test-task.yml
